scss_files: 'source/_sass/*.scss'
exclude: 'source/assets/css/style.scss'

linters:
  NameFormat:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true    
  VendorPrefix:
    enabled: true
