gems:
- bourbon
- neat

timezone:    America/Los_Angeles
highlighter: pygments
markdown:    kramdown
permalink:   /:year/:month/:title/
url: https://robknight.net
cdn: https://d2tpzfmmlcqxf6.cloudfront.net

# Structure configuration
source: ./source
destination: ./build
exclude: [.jekyll-metadata]

title: Rob Knight
tagline: This is where I play.
description: "Web developer, photographer from Santa Cruz, California."

## Custom Variables ##
# Owner/author information
author:
  name: Rob Knight
  bio: "I like to make things and fix things."
  avatar: avatar.png
  email: hello@robknight.net
  github: knice
  instagram: robknight
  twitter: robknight


# Links to include in top navigation
# For external links add external: true
links:
- title: About
  url: /about
- title: Archive
  url: /archive
- title: Instagram
  url: https://instagram.com/robknight
- title: Flickr
  url: http://www.flickr.com/photos/rknight
