gems: [bourbon, neat, jekyll-assets]

timezone:     America/Los_Angeles
markdown:     kramdown
permalink:    /:year/:month/:title/
baseurl:      /
url:          https://robknight.net
cdn:          https://d2tpzfmmlcqxf6.cloudfront.net

title:        Rob Knight
tagline:      This is where I play.
description:  "Web developer, photographer from Santa Cruz, California."

## Structure & configuration ##
source:       ./source
destination:  ./build
exclude:      [.jekyll-metadata, .asset-cache]

assets:
  digest: true

collections:
  projects:
    output: true
    permalink: /project/:path/

## Custom Variables ##
author:
  name:       Rob Knight
  bio:        "I like to make things and fix things."
  avatar:     avatar.png
  email:      hello@robknight.net
  github:     knice
  instagram:  robknight
  twitter:    robknight
  flickr:     rknight
  pinboard:   robknight
