timezone:     America/Los_Angeles
markdown:     kramdown
permalink:    /:year/:month/:title/
cdn:          https://d2tpzfmmlcqxf6.cloudfront.net
tagline:      This is where I play.

title:        Rob Knight
description:  "Web developer, photographer from Santa Cruz, California."
url:          https://robknight.net

## Structure & configuration ##
source:       ./source
destination:  ./build
exclude: [
  .jekyll-metadata
]

google_site_verification: o7315rHAGpao7cw1C4iyb9RjaMIDQwpD8YgoAygnu0U

twitter:
  username: robknight
  card: summary

social:
  name: Rob Knight
  links:
    - https://twitter.com/robknight
    - https://www.facebook.com/kneatly
    - https://www.linkedin.com/in/rknight
    - https://github.com/knice

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate  

collections:
  projects:
    output: true
    permalink: /project/:path/

## Custom Variables ##
author:
  name:       Rob Knight
  bio:        "I like to make things and fix things."
  avatar:     avatar.png
  email:      hello@robknight.net
  twitter:    robknight
  github:     knice
  instagram:  robknight
  flickr:     rknight
  pinboard:   robknight